version: 2

jobs:
    build:
        working_directory: ~/zwitterion
        docker:
            - image: circleci/node:8.11.3@sha256:af7b81b839b0e11acc422e59ca52e42b3bb400f7246d81267d1217c89bc7ae07
        steps:
            - checkout
            - run:
                name: Set permissions
                command: sudo chown -R circleci /usr/local/lib/node_modules && sudo chown -R circleci /usr/local/bin
            - run:
                name: Install Electron dependencies
                command: sudo apt-get update && sudo apt-get install xvfb libgtk-3-dev libxtst6 libXss1 Libgconf-2-4 libnss3 libasound2
            - run: npm install
            - run: npm test
    release:
        working_directory: ~/zwitterion
        docker:
            - image: circleci/node:8.11.3@sha256:af7b81b839b0e11acc422e59ca52e42b3bb400f7246d81267d1217c89bc7ae07
        steps:
            - checkout
            - run: npm install
            - run: npx semantic-release

workflows:
    version: 2
    test_and_release:
        jobs:
            - build
            - release:
                requires:
                    - build
                filters:
                    branches:
                        only:
                            - master
